name: RoarZone Update

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run Decrypt and Update
        env:
          ZIP_PASS: ${{ secrets.ZIP_PASS }}
        run: python decrypt.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sys_config_cache_v9.m3u internal_data_v9.json
          git commit -m "Update Secret Playlist"
          git push
          
