name: RoarZone Ultimate Bypass

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pip install undetected-chromedriver requests
          sudo apt-get update
          # libgconf-2-4 বাদ দেওয়া হয়েছে
          sudo apt-get install -y xvfb libxi6 google-chrome-stable

      - name: Run Script with Virtual Display
        run: |
          xvfb-run --server-args="-screen 0 1920x1080x24" python Script/RoarZone.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "🔄 Refresh Token via Undetected Driver" || echo "No changes"
          git push
